name: Postman Tests
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: 14
#      - name: Install dependencies
#        run: npm install
#      - name: Cypress Test Run
#        id: cypress-results
#        run: npx cypress run --record --key d87b9470-6f9a-4d92-9574-75c70f78bbb5
#      - name: Install Postman CLI
#        run: |
#          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: 'postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}'
          timeout_seconds: 5
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackmsg
      - name: Run Test
        run: >
          newman run https://api.getpostman.com/collections/${{secrets.POSTMAN_COLLECTION}}?apikey=${{secrets.POSTMAN_API_KEY}}
          -e https://api.getpostman.com/environments/${{secrets.POSTMAN_ENV_STAGING}}?apikey=${{secrets.POSTMAN_API_KEY}}
          -r slackmsg
          --reporter-slackmsg-collection 'PostMan Test Collection-GoPuls'
          --reporter-slackmsg-environment 'Staging Env'
          --reporter-slackmsg-webhookurl ${{secrets.SLACK_TESTS_NOTIFICATIONS}}
        continue-on-error: true
